service:
  type: ExternalName
  externalName: [host externo]
  port: 80

ingress:
  enabled: true
  className: nginx
  annotations: 
    nginx.ingress.kubernetes.io/upstream-vhost: [host externo]
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: nginx
  hosts:
  - host: exemplo.com.br
    paths:
      - path: / 
        pathType: ImplementationSpecific
  tls:
    - secretName: exemplo-tls
      hosts:
        - exemplo.com.br