apiVersion: v1
kind: Service
metadata:
  name: {{ include "gam.fullname" . }}
  labels:
    {{- include "gam.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  {{- if eq .Values.service.type "ExternalName" }}
  externalName: {{ .Values.service.externalName }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      protocol: TCP
      name: http
  selector:
    {{- include "gam.selectorLabels" . | nindent 4 }}